library: ./beets.db
directory: ./library
plugins: spotify
import:
    move: yes
    copy: no
    log: ./beets.log
    write: yes
    resume: ask
    incremental: yes
    incremental_skip_later: no
    musicbrainz:
        external_ids:
            spotify: yes
