library: ./local/beets.db
directory: ./local/library
plugins: spotify
import:
    move: yes
    copy: no
    log: ./local/beets.log
    write: yes
    resume: ask
    incremental: yes
    incremental_skip_later: no
    musicbrainz:
        external_ids:
            spotify: yes
